### ISSUE TITLE
Chrome disabling Streamkeys because of violation of Chrome Web Store policy.

### ISSUE THREAD

**Issue by wtesler** [berrberr/streamkeys#424] opened 2018-05-02 09:50 UTC
Just today, I have found that Chrome is disabling Streamkeys by default because of this violation. I'm not sure why this is being caused but it seems important to look into.

![streamkeys](https://user-images.githubusercontent.com/2490505/39517063-9e105138-4db3-11e8-88f9-17d2fd69a00a.PNG)

**Comment by elieux** [comment] 2018-05-02 10:08
Duplicate of #416, I guess.

**Comment by h4uja2** [comment] 2018-05-02 11:29
Any news? There are no good alternatives to this extensions.

**Comment by NessDan** [comment] 2018-05-03 20:46
But @mkarpoff there could be a security reason behind why it was taken down. From what I gather, it was removed for having a version of jQuery?

**Comment by wetfirer** [comment] 2018-05-14 20:46
Stupid, stupid. Stupid. Thanks guys that you managed to put it back here. I hope to see it soon again on google store.

**Comment by metaflow** [comment] 2018-05-30 08:28
@berrberr are you aware of that?

**Comment by dcormier** [comment] 2018-05-30 15:46
It seems to be resolved. It's available on the Chrome web store again. But if it was disabled already it might still show that it violates the store policies. I reenabled and refreshed and that message went away.

**Comment by frederickjh** [comment] 2018-05-30 16:37
It is still showing the warning here in:
![image](https://user-images.githubusercontent.com/864159/40734255-2dec5262-6438-11e8-857d-37a6cfb9bbb4.png)

for the latest version like this:
![image](https://user-images.githubusercontent.com/864159/40734272-39ddfa8a-6438-11e8-9924-382e35207b5f.png)

@dcormier, what did you refresh  that the message went way?

**Comment by dcormier** [comment] 2018-05-30 18:34
@frederickjh, I refreshed the extensions page after re-enabling it and the warning went away. It's back now, though.

However, I just installed it from the Chrome web store on a different Chrome profile with no issues.

![image](https://user-images.githubusercontent.com/216265/40740239-4f1e2086-6416-11e8-8b8c-36406b42ea77.png)

![image](https://user-images.githubusercontent.com/216265/40740219-3aea50b2-6416-11e8-9a38-9d735c2ae941.png)

**Comment by wtesler** [comment] 2018-05-30 18:47
​After removing it from Chrome and re-adding it (1.75), the warning went
away for me.

**Comment by mfkp** [comment] 2018-06-01 01:05
Still getting the same behavior, where it works for a bit when installed, then stops working after an hour or so.


![screenshot](https://s3.us-west-2.amazonaws.com/mfkp-screenshots/2018/05/31/chrome_2018-05-31_18-04-43.png)

**Comment by fgblomqvist** [comment] 2018-06-03 19:10
Getting the same result as mfkp.
Any updates on this @berrberr ?

**Comment by quisse** [comment] 2018-06-12 08:49
https://github.com/berrberr/streamkeys/issues/416

**Closed** 2018-09-30 04:32 UTC
