### ISSUE TITLE
Add an "Play/Pause last source"

### ISSUE THREAD

**Issue by ravanscafi** [berrberr/streamkeys#133] opened 2015-07-23 18:50 UTC
Scenario: 
1. I'm listening to some music (deezer/spotify/rdio, whatever)
2. Someone sends me a link from youtube.
3. I manually pause the video (because i'm listening to some music!) and keep it open to watch later.
4. For some reason I need to pause my music.
5. Music pauses. Video starts.

It happens to me every freaking day. And with a lot of videos. It would be cool to control only one source.
I know that I can pause all, but when I start again, it will start all of then.

And this is only one scenario, I know that must be many others.

**Comment by berrberr** [comment] 2015-07-25 19:52
Yeah this is annoying and also happens to me too. It has been talked about in the past but I haven't heard a great solution yet.

The problem is, how should the extension decide which tab is the "correct" player? There is not really a way to do this programmatically, there will have to be user input at some point (ie, it's not possible to distinguish a youtube "music" tab from "video").

Right now you *can* disable individual tabs by using the popup. It's certainly not ideal (takes 3 clicks) but it works.

Possible solutions:
1. Add a "set primary tab" button to the popup. A primary tab means that by default play/pause commands will only be sent to that tab. The user can still manually toggle other tabs to be enabled after setting a primary tab via the popup.
2. Add a "start disabled" option for every site. If you set start disabled on for youtube then every youtube tab you open will have to be manually toggled on (via the popup) before it receives commands.

If you have any suggestions I would love to hear :+1: I agree that this is annoying and needs to be fixed

**Comment by Illyism** [comment] 2015-07-26 15:45
Can you combine a ctrl/alt/shift/mod/super/win key with a media key?

If so, you could:

* shift+play = Pause all video
* ctrl+play = Play/Pause current visible tab

**Comment by berrberr** [comment] 2015-07-27 06:43
Chrome commands doesn't let you add a modifier key to media key shortcuts :(

But even if you could, I think the problem is when you open up (for example) a youtube video to watch later and you keep doing something else. Then sometime later you press pause...you are probably not focused on the music player tab, but you want the pause to be sent to that player only and not the video that you opened before.

Problem is from the extension's perspective it can't really distinguish between what is a player vs a "non-player" (ie. video) without some kind of user input...

Maybe a hotkey could be added to "disable active tab", so when you load up the video initially you press the hotkey so Streamkeys commands won't be sent to the tab (note this functionality exists already via the popup, but maybe a hotkey is better than clicking?)

**Comment by Bomberlt** [comment] 2015-09-22 11:00
I think second solution where you set "start disabled" option would be really good for people who rarely listen music using YouTube and mostly just watch some videos on it.

Also by @rscafi scenario, user could just disable YouTube all along and use YouTube only for videos not music and then there is no problem with determining which player is correct.

**Comment by Dangelo123** [comment] 2016-03-29 18:32
Also happens to me.
I like to have some playlist tab's fix in my session, and if I want to use streamkeys I can't do that for the reasons mentioned above.

**Comment by rscafi** [comment] 2016-03-29 18:45
Perhaps we could leverage pinned tabs and interact with them (if any) instead of regular tabs?
By doing this, one could pin the "music tab" and leave the others as usual

**Comment by MHendricks** [comment] 2017-01-27 05:32
What about for video sites like youtube a option to only control the active tab per window. If you are listening to music this may not be ideal, but for video I almost always want to be able to see the video I'm watching. I don't often have multiple chrome windows open, but when I do I personally rarely would have more than one video tab active at once.

The main reason I use this extension is so I can pause/play a video on my second monitor while I am playing a video game on my first monitor, assuming the video game doesn't consume the media keys itself.

> Right now you can disable individual tabs by using the popup. It's certainly not ideal (takes 3 clicks) but it works.

3 clicks + disabling 4 of the 5 tabs I have open. You could add a button that would disable all but the one you click on in the popup. Or holding shift or control when clicking on the disable button would disable all but the one you click on.

> Maybe a hotkey could be added to "disable active tab", so when you load up the video initially you press the hotkey so Streamkeys commands won't be sent to the tab (note this functionality exists already via the popup, but maybe a hotkey is better than clicking?)

This would not be useful to me unless it persists when I close and reopen chrome. And besides having to remember to deactivate every video tab I open every time I open it seems annoying to me. I've had the same 5 youtube playlist tabs open for over 6 months and I turn my computer off every day when I go to work. 

Though the reverse could probably work. A global hot key that disables all but the active tab(per window).

**Comment by jmcken8** [comment] 2017-04-14 23:01
Maybe I'm oversimplifying things here but there's an "isPlaying" option in BaseController right? And you know which windows have had a script injected (or at least it's simple to just send a message to each asking if they do). Why not loop through all playable windows and pause the first one that's playing?  Continuous presses would pause music sources one by one.

Restarting playing would be a little more difficult... This should be thought through more but you could do some ordering like:
- current tab
- the last N tabs the user has visited since last pressing 'pause'
- the last tab paused, 2nd last tab paused if tab has been closed, etc.

**Comment by Rohaq** [comment] 2017-05-15 01:12
I'd love to see some kind of priority order option added for sites under the same main priority too.

Maybe by assigning them an incrementing number when they're opened, and then adding a "Media keys control most recent/oldest tab" option?

You could even integrate it into the existing priority system by using floats, so if a base site's priority is 4, and it's the sixth tab in that priority that you have open, assign it a priority of 4.000006, then next 4.000007, etc. Another site is open with a base priority of 2, but is the first tab, so it gets assigned 2.000001, etc., and the ordering rules remain the same.

**Closed** 2018-09-30 04:34 UTC
Labels: enhancement
